### ISSUE TITLE
<dialog> is baseline but still in the top 3 features people can't use in State Of HTML 2023

### ISSUE THREAD

**Issue by captainbrosset** [web-platform-dx/web-features#1134]
See https://2023.stateofhtml.com/en-US/usage/#html_interoperability_features
In the free-form text answers, people mention missing features and ongoing issues with `<dialog>`, however, it's marked as baseline in our repo.

A few example comments:

- "Dialog element (is it accessible yet?)"
- "dialog.showModal (Safari, a11y)"
- "dialog due to Firefox"
- "Proper dialogs because of iOS, e.g. showModal"
- "Dialogs where dialog content is changed with ja (paint loss in safari)"

I don't have insights into what these issues are, but I think we should check whether this should impact the status of this feature. A few possibilities: 

- Maybe the survey ran when the feature wasn't supported everywhere yet.
- Maybe the feature can be used fine, but some additional pieces are not yet available everywhere. In which case we might consider renaming the feature to "initial support", as we did with other features.
- Or perhaps there are some important issues preventing web developers from using this feature in production, in which case we should consider demoting the feature.

**Comment by atopal** [comment]
a few more: 
* <dialog> because slightly older iOS versions
* backdrop pseudo is not cross browser
* Dialog (::backdrop)

[BCD says](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop) that backdrop on the Dialog element is supported across all major browsers and has been for a while, but there are some issues mentioned here: https://a11y-dialog.netlify.app/further-reading/dialog-element/

**Comment by captainbrosset** [comment]
This issue came up in our bi-weekly Baseline call ([notes](https://docs.google.com/document/d/1ree75ImLZjf60lTZ3BhCaLHygxgywr7SBXp-q0xPs8A/edit#heading=h.vjtbcnpm8lgv)).

Kadir found this: https://a11y-dialog.netlify.app/further-reading/dialog-element/ from @KittyGiraudel, which says:

> The native HTML <dialog> element has come a long way. While it used to be very inconsistent, not to mention somewhat unfinished, it is now in a pretty healthy place and [can generally be used](https://www.scottohara.me/blog/2023/01/26/use-the-dialog-element.html) — provided one is aware of the [remaining caveats](https://a11y-dialog.netlify.app/further-reading/dialog-element/#remaining-caveats).

The remain caveats being:


> * Clicking outside the dialog does not close the dialog in some browsers such as Chrome.
> * The ::backdrop pseudo-element only shows when programatically opening the dialog, not when using the open attribute.
> * Default styles are left to the browsers’ discretion and can be inconsistent.
> * The [alert dialog pattern](https://a11y-dialog.netlify.app/advanced/alert-dialog) (role="alertdialog") does not work with the <dialog> element.
> * The events emitted by the <dialog> element are a little confusing (there is both cancel and close but no open) and not very reliable (only fired in certain situations).
> * Using the &lt;dialog> element still requires JavaScript (unlike &lt;details> for instance).

Seems like the Baseline status is valid for this feature then. Closing the issue.
