### ISSUE TITLE
Enable issue templates for this repository

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#1156]
I'd like to add a template for missing features. Following the documentation in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository I don't see the "Issues" checkbox under settings. I probably don't have the right level of access.

@dontcallmedom @tidoust could either of you help enable this?

**Comment by dontcallmedom** [comment]
added you as admin; that said, I think you only to add md files to .github/ISSUE_TEMPLATE

**Comment by foolip** [comment]
Thank you @dontcallmedom! I think you're right, the checkbox is for issues as a whole, not issue templates. So I didn't need to change anything. I've sent https://github.com/web-platform-dx/web-features/pull/1163 now and we'll see if it works.

**Comment by foolip** [comment]
It worked!
