### ISSUE TITLE
Typo in array-by-copy description

### ISSUE THREAD

**Issue by sammyhawkrad** [web-platform-dx/web-features#1217]
[array-by.copy](https://github.com/web-platform-dx/web-features/blob/5ec195275be14e583e7e5111faa070ac9f1430e6/features/array-by-copy.yml#L2) has this description:

The toReserved(), toSorted(), toSpliced(), and with() methods of arrays and typed arrays return changed copies of arrays. They stand in contrast to methods such as sort() or reverse() that change arrays in place.

I believe toReserved() might be a typo and should rather be toReversed().

Discovered on [Array by copy](https://webstatus.dev/features/array-by-copy?start=25)  and also reported here https://github.com/GoogleChrome/webstatus.dev/issues/336

**Comment by sammyhawkrad** [comment]
Fixed by #1218

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/1218 is now merged, thanks @sammyhawkrad!
