### ISSUE TITLE
Baseline Proposal

### ISSUE THREAD

**Issue by atopal** [web-platform-dx/web-features#132]
[Some time ago](https://github.com/web-platform-dx/feature-set/issues/1), I put up a proposal for Baseline feature set. Now, that we had some discussion of that, I thought, I'd bring it back here for further discussion as a proposal for something we maintain as part of this group:

### Motivation
Developers tell us that [keeping up with changes to the platform is a major issue for them](https://web.dev/deep-dive-into-developer-pain-points/). Due to the fragmented nature of the platform, the frequent browser releases and interoperability issues, developers have a hard time knowing when features are finally ready to use after hearing about them for a long time. This proposal attempts to address that fragmentation by providing developers with a profile of the web platform that we think will work for most developers most of the time.

While any individual developer can decide on their browser support matrix based on their audience numbers, frameworks, CMSes, libraries and other parts of the web ecosystem have to define a browser support matrix in the absence of that analytics data. For the longest time IE11 defined the upper bound for which features could be used for a large number of developers. With the sunsetting of IE 11 the question is now what constitutes that bar.

### Baseline
The Web Platform Baseline is the set of features that is natively supported in the core browser set (see below) for at least two major versions. This feature set is what we believe most developers will consider the stable feature set of the web platform most of the time.

Users using exclusively evergreen browsers means that the feature set will change regularly instead of being fixed for years. Identifying and agreeing on a core browser set will provide guidance for developers in that new world. 

Web developers can check on MDN or caniuse.com whether a feature is in Baseline and can be assured that the feature is ready to be used.

With the definitions above we can also compare the set of features available to developers between two moments in time. This is useful when we want to talk about which features are available now that were not available 12 months ago. It allows us to define moments in time and declare a Web Platform Baseline 2024 that covers all features that were usable in Baseline at that moment in time, so we can reference that feature set and highlight changes.

### Core browser set
The core browser set is what we believe most developers need to support most of the time in the absence of specific constraints. It takes into account [usage numbers](https://caniuse.com/usage-table), developer expectations and [existing support in](https://make.wordpress.org/core/handbook/best-practices/browser-support/) [the ecosystem](https://angular.io/guide/browser-support).

Browser | Supported versions | Major version cadence
-- | -- | --
Chrome | 2 most recent major versions | Monthly
Firefox | 2 most recent major versions | Monthly
Edge | 2 most recent major versions | Monthly
Safari | 2 most recent major versions | Annually
Safari on iOS | 2 most recent major versions | Annually
Chrome on Android | 2 most recent major versions | Monthly

The core browser set is not a fixed entity, as developer expectations and user numbers change, we’ll update the core browser set to reflect the current state.

Commitment
We’ll commit to maintaining the classification of features that are in Web Platform Baseline on an ongoing basis and to update the classification as browsers are released and features become available. This will be done in the [Feature Set repo](https://github.com/web-platform-dx/feature-set) of the [WebDX CG](https://www.w3.org/blog/2022/11/webdx-improving-the-experience-for-web-developers/). If you have any feedback or would like to contribute, please use the feature set repo.

**Comment by romainmenke** [comment]
_I am unsure if this is the right place to give feedback on [Baseline](https://web.dev/baseline/) in general, so please point me in the right direction if this is not it :)_

-----

I am a bit confused about what the focus and intention of baseline is.

Is the purpose to determine a baseline of browser versions that most developers need to support most of the time and map those version to features that are included therein?

Or is the purpose to indicate when a feature has reached a certain level of stability and thus makes it ready for developers to learn more about.

I think these are very different things and that it doesn't help end users to mix these.

Clearly indicating that a feature is implemented by all major vendors is very valuable to developers. But promoting a culture where only the last two versions of only the 3 major vendors are supported can be very harmful.

Has there been any discussion about potential adverse affects of this?
Has there been any research into the adoption of latest browsers versions when considering location, wealth, a11y needs, ...

**Comment by Mantish** [comment]
I totally agree with @romainmenke's concern.
Looking at how this is displayed in https://web.dev/ and https://developer.mozilla.org/ with all green checkmarks, I think that this may end up causing a negative effect for end users.
Considering how this is gonna be used in documentation websites, would you consider a more conservative approach for the baseline? Just looking at the Chrome numbers from https://caniuse.com/usage-table you can see there are a lot of  people up to 4 versions behind the most recent one.

**Comment by atopal** [comment]
These are really good questions.

Re stable specs, standards orgs already have ways to indicate which specs are stable. They all do that on a per feature basis through the staging process, but many of them also have that on a regular basis for the whole technology. ECMAscript has annual releases, the last one being [ECMAScript2022](https://262.ecma-international.org/) and the CSSWG does CSS snapshots ([CSS Snapshot 2022](https://www.w3.org/TR/css-2022/)). However, as the CSS WG states in the abstract: "The primary audience is CSS implementers, not CSS authors, as this definition includes modules by specification stability, not Web browser adoption rate".

The assumption we are basing this work on is that web developers care more about browser availability then spec status, whether that is to learn about features or to use them, and there currently exists no comprehensive and up to date view of the web platform as implemented by browsers.

I also want to address the issue of coverage. There are at least two needs in tension here: the need to be comprehensible and the need to be comprehensive. Developers tell us that one of the major issues they have is keeping up with the changes to the web platform, so we want to make it easy for them to tell what they can use today and what has changed recently. However, we also know that no two developers are identical and it's simply not possible to come up with a definition that will fit every case. So, we are shooting for something that will work for most developers most of the time.

Hopefully, on the path to that, we'll get better at identifying and providing reliable browser usage data, but also better at understanding developer expectations around availability and better at communicating the status of features. 

Specifically about the numbers you've mentioned. I wasn't aware that Statcounter counts all mobile browsers as the last version of that browser. caniuse.com shows usage relative data for mobile browsers based on Statcounter data, which lead to me to believe the data is available. Do you have a link for me to read up about that issue?

Since it is unintuitive, I also want to clarify the "last 2 versions of major browsers". With the browserlist calculator, you'll get the number for just the last two major versions (which btw would be around 78% for major versions), but that's only the case when a feature has simultaneously landed across all browsers. That is basically never the case. Usually one or more browsers will have implemented a feature before the final browser has an implementation, so what we are actually tracking here is much more than jus the lat two major versions.

**Comment by tidoust** [comment]
> Since it is unintuitive, I also want to clarify the "last 2 versions of major browsers". With the browserlist calculator, you'll get the number for just the last two major versions (which btw would be around 78% for major versions), but that's only the case when a feature has simultaneously landed across all browsers. That is basically never the case. Usually one or more browsers will have implemented a feature before the final browser has an implementation, so what we are actually tracking here is much more than just the lat two major versions.

Given that the data tracks the first browsers versions that added support for a given feature, perhaps we could use audience coverage calculators for computing monitoring a slightly more precise audience coverage for baseline features. This would allow us to back the baseline selection criteria with quantitative data, and to trigger alarms if the computed audience coverage of a baseline feature ever goes below a certain threshold (e.g. 85%?), to signal a situation that seems abnormal.

**Comment by romainmenke** [comment]
> Specifically about the numbers you've mentioned. I wasn't aware that Statcounter counts all mobile browsers as the last version of that browser. caniuse.com shows usage relative data for mobile browsers based on Statcounter data, which lead to me to believe the data is available. Do you have a link for me to read up about that issue?

https://github.com/Fyrd/caniuse/issues/2413#issuecomment-206673558

-------

My concern is specifically that Baseline is being communicated as a tool that developers can use as a moving target for their own projects.

This is a very different thing from having an indicator on docs that a feature is stable and ready for learning.

I personally think it needs to be focussed more on the learning/teaching aspect.

> I also want to address the issue of coverage. There are at least two needs in tension here: the need to be comprehensible and the need to be comprehensive. Developers tell us that one of the major issues they have is keeping up with the changes to the web platform, so we want to make it easy for them to tell what they can use today and what has changed recently. 

This is very valuable, but it is very different from using the same concept as a support target when building an actual website.

If the aim is to communicate when something is ready for learning it makes sense to just track latest release + 1 (so minors for Safari). If a feature has an implementation in all three engines in latest + 1, it is a strong signal that the feature is stable.

But this must not be confused with a support target for individual websites.

--------

> This would allow us to back the baseline selection criteria with quantitative data, and to trigger alarms if the computed audience coverage of a baseline feature ever goes below a certain threshold (e.g. 85%?), to signal a situation that seems abnormal.

This again makes me think that we are talking about a general support target, not when something is ready for learning.

-------

I also think it is weird that no one was consulted from browserslist, caniuse, polyfill.io, postcss-preset-env, core-js, babel, ... (correct me if I am wrong about this)

Myself and other maintainers of these projects have years of experience in this field.

**Comment by dfabulich** [comment]
Having thought about this further, I think the ideal fix for this is just to never say "Baseline" without a year associated with it, as I propose in #175.

If we say that `<dialog>` is "Baseline 2023", I can decide for myself whether I want to target Baseline 2023, or Baseline 2022, or an older year. (When I shipped `<dialog>` to end users in March of this year, I got a bunch of support tickets from users on Safari 14.)

I note that import maps just shipped in Safari 16.4, and will therefore have support in 2 major browser versions when Safari 17 ships in fall of this year. If that means that import maps will be considered "Baseline 2023" in October, then so be it, but it just means that I won't target Baseline 2023 until 2024 or 2025.

**Comment by romainmenke** [comment]
A good analysis on the drawbacks of the current Baseline : https://molily.de/browser-compatibility-baseline/

**Comment by atopal** [comment]
I think it makes sense to clarify that Baseline is not exclusively about signaling that something is ready to be learned about. As I mentioned standards orgs already have ways to signal that a feature is stable, but there is no equivalent signal for` Is this feature widely available`? Also, I don't think it makes sense to treat "ready to learn about" separately from "ready to be used/widely available". The vast majority of developers wants to hear and learn about things they can use now, not some time in the future.

>> I also think it is weird that no one was consulted from browserslist, caniuse, polyfill.io, postcss-preset-env, core-js, babel, ... (correct me if I am wrong about this)

> Myself and other maintainers of these projects have years of experience in this field.

We have consulted with BCD and caniuse.com, but obviously could have cast a wider net. That said, this is just the starting point for Baseline, and hopefully we can work on this together within the WebDX CG. That's exactly why we made it public now, to gather feedback and iterate before we go deep and wide. 


@dfabulich import maps is a good point. By September 2023 it will probably still have relatively low coverage, and that would be an issue with the current core browser set. We are already planning on having Baseline 23, Baseline 24 as feature sets, but I'm not sure how useful that will be in determining support on a per feature basis, as that too would only be a proxy for coverage.

**Comment by atopal** [comment]
Also, thank you for all the thoughts in here. We're still currently collecting feedback and will review over the next few weeks to determine next steps to iterate on Baseline

**Comment by romainmenke** [comment]
> We have consulted with BCD and caniuse.com, but obviously could have cast a wider net. That said, this is just the starting point for Baseline, and hopefully we can work on this together within the WebDX CG.

Yes, I think it would be valuable to also capture the perspective of projects that focus on increasing cross browser and older browser version support. Only having the insights of BCD and caniuse.com is too limiting and one sided imho.

What is the preferred way for this?
I can take the time to write some experience reports as a starting point?

**Comment by foolip** [comment]
@romainmenke I'll let @atopal give advice as well, but if you haven't already done so you can join the CG at https://www.w3.org/community/webdx/. Meetings are un Thursdays, and I think this is the "invite" for it:
https://beta.w3.org/events/meetings/c2a4cb5c-8146-4ba0-ad37-2a3f39de92d0/?recurrenceId=20230131T160000

**Comment by tidoust** [comment]
Closing this issue as addressed: the group discussed and converged on a [baseline definition](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md). That definition has also been deployed to MDN and Can I Use. Problems with the current baseline definition or suggestions for improvement should be raised as specific issues.
