### ISSUE TITLE
Dist refresh workflow does not trigger tests after pushing

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#1320]
On https://github.com/web-platform-dx/web-features/pull/1304, after the push and the label was removed, the checks don't start. This is almost certainly because a push by GitHub Actions cannot trigger another GitHub Actions workflow.

The workaround is to close and reopen the PR.

@ddbeck FYI

**Comment by captainbrosset** [comment]
@tidoust and I faced the same problem in https://github.com/web-platform-dx/web-features-explorer/pull/14

**Comment by ddbeck** [comment]
Yeah, I've been banging my head against this problem. Maybe y'all would have a look at https://github.com/web-platform-dx/web-features/issues/1158 and give your thoughts on approaches there?
