### ISSUE TITLE
BCD key css.properties.position-try-options doesn't exist

### ISSUE THREAD

**Issue by captainbrosset** [web-platform-dx/web-features#1344]
https://github.com/web-platform-dx/web-features/blob/af41594bcfd4bac9050b5c10632d5bbf9bb0c170/features/anchor-positioning.yml.dist#L158-L163 references the `position-try-options` CSS property which doesn't exist in BCD.

**Comment by captainbrosset** [comment]
The name was changed in https://github.com/mdn/browser-compat-data/pull/23667

**Comment by captainbrosset** [comment]
I think we only need to bump BCD for this to go away.

For information, I found this out because the web-features-explorer's build was failing: https://github.com/web-platform-dx/web-features-explorer/actions/runs/9866214981

The reason it is failing is that it uses both web-features and BCD as two sources of data which it combines to create interesting features.
Knowing which version of BCD was used by web-features would avoid this issue. Instead of always using the latest release, we would use whichever release was used by web-features, and would never have incompatible data.

**Comment by foolip** [comment]
This will be fixed by https://github.com/web-platform-dx/web-features/pull/1346.
