### ISSUE TITLE
Iframe credentialless

### ISSUE THREAD

**Issue by swissspidy** [web-platform-dx/web-features#1389]
### Specification

https://wicg.github.io/anonymous-iframe/

### Description

Iframe credentialless (formerly known as [anonymous iframe](https://developer.chrome.com/blog/anonymous-iframe-origin-trial)) enables embedding third-party iframes that do not set [Cross-Origin-Embedder-Policy (COEP)](https://web.dev/security-headers#coep), which is a requirement for websites to use privileged features including [SharedArrayBuffer](https://developer.chrome.com/blog/enabling-shared-array-buffer)

### Browser support

Chromium only at this point, see https://developer.mozilla.org/en-US/docs/Web/Security/IFrame_credentialless

**Comment by foolip** [comment]
This is a draft feature at https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/anonymous-iframe.yml which should be fairly straightforward to finish up and publish. @swissspidy if you're feeling up for it, there are instructions in https://github.com/web-platform-dx/web-features/blob/main/features/draft/spec/README.md.

**Comment by swissspidy** [comment]
Cool, just gave it a go at #1460
