### ISSUE TITLE
Nominating 3 new peers

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#1474]
Hi owners @Fyrd @dfabulich @ddbeck @Elchi3 @jgraham @atopal @LeoMcA!

I'd like to nominate 3 new peers, my colleagues @kosamari @petele @tropicadri who have recently contributing to web-features and have plans to keep going to at least 100 new features.

Write access would be convenient so that we can more easily have shared branches in this repo and sort out merge conflicts, which we have recently been creating...

Per https://github.com/web-platform-dx/web-features/blob/main/GOVERNANCE.md#peers we vote to confirm new peers. There are 8 owners, so 5 is a majority. I hereby the first vote in favor :)

**Comment by atopal** [comment]
Same here! +1

**Comment by jgraham** [comment]
Did you by any chance mean @kosamari ?

**Comment by foolip** [comment]
> Did you by any chance mean @kosamari ?

Yes, edited! Thanks!

**Comment by ddbeck** [comment]
Works for me. 👍

**Comment by jgraham** [comment]
This seems fine to me.

**Comment by Elchi3** [comment]
Works for me 👍 
Welcome to our new Peers!

**Comment by dfabulich** [comment]
👍

**Comment by ddbeck** [comment]
I've merged the docs PR and sent GitHub invites to the new peers. 🎉
