### ISSUE TITLE
View Transition Classes

### ISSUE THREAD

**Issue by hvanops** [web-platform-dx/web-features#1491]
### Specification

https://drafts.csswg.org/css-view-transitions-2/#view-transition-class-prop

### Description

This feature introduces a new CSS property view-transition-class which allows the developer to specify one or more view transition classes. The developer can then select the ViewTransition pseudo elements using these classes (e.g. ::view-transition-group(*.class)).

This is an extension to the ViewTransition API that simplifies styling of view transition pseudo elements in a similar way that CSS classes simplify styling of regular DOM elements.

**Comment by jamesnw** [comment]
This was added in #1914. Thanks!
