### ISSUE TITLE
Snapevents

### ISSUE THREAD

**Issue by hvanops** [web-platform-dx/web-features#1522]
### Specification

[Spec review for Snap Events · Issue #943 · w3ctag/design-reviews · GitHub](https://github.com/w3ctag/design-reviews/issues/943#:~:text=https%3A//drafts.csswg.org/css%2Dscroll%2Dsnap%2D2/%23snap%2Devents)

### Description

Snap Events allow developers to reliably listen for when the "snap target" of a scroller changes and perform style adjustments as desired.

CSS scroll snap points are often used as a mechanism to create scroll interactive "selection" components, where selection is determined with javascript intersection observers and a scroll end guesstimate. By creating built-in events, the invisible state will become actionable, at the right time, and always correct. This feature adds two JavaScript events:

- Snapchanging: This event gives developers a hint during a scroll operation that the user agent intends to snap the scroll container to a new snap target based on the scrolling input so far.

- Snapchanged: This event lets developers know that the element to which a scroller is snapped has changed, and fires at the completion of a scroll operation (including snapping)

**Comment by jamesnw** [comment]
This was added in #2103. Thanks!
