### ISSUE TITLE
Merge Growable SharedArrayBuffer + Resizable ArrayBuffer?

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#1558]
@syg has pointed out that these two features were part of the same TC39 proposal:
https://github.com/tc39/proposal-resizablearraybuffer

They were shipped together as well. Do web developers really think about these as separate features, or should we merge them?

cc @Elchi3 @captainbrosset @ddbeck who were involved in https://github.com/web-platform-dx/web-features/pull/1242.

**Comment by syg** [comment]
They _can_ be separately used but I also don't think all the web implementations made them both available at the same time, so in practice they're thought of as one IMO.

**Comment by Elchi3** [comment]
I have no strong feelings here. What would a merged feature be called?

growable-sharedarraybuffer-resizable-arraybuffer.yml
name: Resizable ArrayBuffers and growable SharedArrayBuffer
description: The `resize()` method of an `ArrayBuffer` and the `grow()` method of a `SharedArrayBuffer`, constructed with the `maxByteLength` option, changes the size of the buffer in place.

**Comment by syg** [comment]
> I have no strong feelings here. What would a merged feature be called?

In conversation I call the feature "resizable buffers".
