### ISSUE TITLE
Clarify how to use the `compat_features` key

### ISSUE THREAD

**Issue by autonome** [web-platform-dx/web-features#1633]
The contribution guide says this key is optional, and has the following description:

> The list of browser-compat-data entries that make up this feature. In many cases, the corresponding browser-compat-data entries already map to the feature ID, and this is therefore not needed.

Does this mean there are times where there's a disjoint between the two? In that case, do you list them all or only the missing ones?

And if there are missing ones, should suggest to file a BCD issue?

**Comment by ddbeck** [comment]
> Does this mean there are times where there's a disjoint between the two? In that case, do you list them all or only the missing ones?

The gist is that the contents of the authored YAML file (i.e., `<feature-id>.yml`) overrules other possible sources of data. This goes for `status` as well. If you provide a `compat_features` value, then the BCD tag is completely ignored. So either provide a complete `compat_features` list or none at all.

I've opened https://github.com/web-platform-dx/web-features/pull/1667 to improve that table entry.

> And if there are missing ones, should suggest to file a BCD issue?

No, that's not necessary. Open Web Docs is working on synchronizing `compat_features` keys with BCD's tags (e.g., https://github.com/web-platform-dx/web-features/pull/1622). That work is partly tracked with https://github.com/openwebdocs/project/issues/208, but I'm putting it on my to-do list now to get some issues in web-features to correspond to that.

**Comment by Elchi3** [comment]
https://github.com/web-platform-dx/web-features/pull/1668 is an example for authoring an override (which we will sync back to BCD automatically soon)
