### ISSUE TITLE
Create `gh-pages` branch

### ISSUE THREAD

**Issue by petele** [web-platform-dx/web-features#1705]
I'm working on the browser vendor agnostic landing pages for Baseline. My plan is to use GitHub Pages in this repo to host the content, specifically using a `gh-pages` branch. (see [step 6b](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll)).

But in order to do that, I need to create the `gh-pages` branch here first, then do a PR from my fork into this repo. According to the [governance doc](https://github.com/web-platform-dx/web-features/blob/main/GOVERNANCE.md), it's not clear if I'm allowed to do that. 

Can I please get an all clear to create the branch here (following the steps in 6b above)? Once that's done, I'll create a PR with the content from my branch to this repo. According to [SO](https://stackoverflow.com/questions/9796370/github-pull-request-to-a-new-upstream-branch), this is the best way of going about it.

Content is currently at https://github.com/petele/web-features/tree/gh-pages and staged at https://petele.github.io/web-features/

**Comment by atopal** [comment]
We discussed this in the WebDX call 2 weeks ago, and everyone present was in favor of it. So +1 from me, and I've added this to the agenda for today's call.

**Comment by ddbeck** [comment]
Oh yikes I wish this had not come up while I was out sick. I would've warned you about a bunch of hazards relating to this. 😅 

My chief concern is that the `gh-pages` branch has some very unpleasant side effects. For example, pages changes can never happen in the same PR as changes to `main`—it's like stuffing docs into a separate repository.

If we're going to do this, then using GitHub Actions to deploy is going to be much, much better: https://github.com/actions/starter-workflows/blob/main/pages/jekyll-gh-pages.yml

**Comment by petele** [comment]
I can go that way too, I felt this was cleaner, but open to going that way. I'll refactor then.

**Comment by petele** [comment]
Created #1706
