### ISSUE TITLE
support multiple paths in `dist --`

### ISSUE THREAD

**Issue by autonome** [web-platform-dx/web-features#1710]
Much feature work involves multiple files. It would be nice to be able to build multiple files without building the whole feature set.

**Comment by ddbeck** [comment]
This should work already. For example, if I comment out a compat feature from `a.yml` and `base.yml`, then run `npm run dist -- features/a.yml features/base.yml`, those files (and only those files) are updated.

Can you provide reproduction steps for a case where this is not working?
