### ISSUE TITLE
`update-drafts` shouldn't modify `draft_date` when there are no other changes

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#1716]
Updating `draft_date` produces lots of noise in the diff on updates. See https://github.com/web-platform-dx/web-features/pull/1715 for an example. In that case, there are no real changes to the feature files, just updates to the dates.

Instead, the script ought to check if there are any differences _except_ the date before writing a file. If the only difference is the date, then the file ought to be skipped. This will also make it easier to find areas we haven't touched recently.

**Comment by autonome** [comment]
This also fixes a dev workflow papercut when merging, b/c these always show as conflicts.
