### ISSUE TITLE
Is YAML a necessity here? Can we just use JSON?

### ISSUE THREAD

**Issue by tabatkins** [web-platform-dx/web-features#1853]
All the data files are YAML currently. I understand that JSON comes with some important limitations (notably comments), but it has the nice property that Python has a built-in module for parsing it; I'll have to pull in a library to parse YAML files. It's not the end of the world, just a minor annoyance.

**Comment by captainbrosset** [comment]
You can actually get the built JSON from any of our releases: https://github.com/web-platform-dx/web-features/releases/tag/v1.4.0
@ddbeck can likely provide more information.

**Comment by ddbeck** [comment]
Yes, @captainbrosset is correct. To consume web-features (as opposed to contributing changes), then the JSON artifacts that Patrick linked to are the way to do it (or the npm package which wraps around `data.json`). The built JSON contains several things that the YAML files do not, such as browser versions and HTML strings instead of Markdown.

We ought to have better documentation on this point.

**Comment by tabatkins** [comment]
Ah, nice! Are those releases done at a similar pace to the actual data updates, or are they manual "whenever it's worth cutting a new release due to program updates" timing?

**Comment by ddbeck** [comment]
Right now I'm getting close to weekly releases, but I'd like to do releases more often, on the same cadence as mdn/browser-compat-data (BCD), which usually releases twice weekly.

That said, though npm you can get a pre-release based on `main` (run `npm install web-features@next`). It wouldn't be hard to make the plain JSON available too. I've filed https://github.com/web-platform-dx/web-features/issues/1860 for that task specifically.

Long-term, I think it would make sense to release the same days that BCD does and for BCD to release a couple of times a day plus any day there's a new browser release (https://github.com/mdn/browser-compat-data/issues/22919).

**Comment by tabatkins** [comment]
Sounds good! And yes, #1860 is precisely what I was about to ask about. ^_^ Thanks then, I'll close this issue.
