### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#20]
Before we get contributions more broadly we need to add a license to the repo.

@dontcallmedom @tidoust what's the typical license for W3C CG repos?

**Comment by tidoust** [comment]
I don't think there is something typical for CG. The same typical licenses as for other open source projects would apply. In no particular order:
- The [W3C Software and Document License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document). Used for code samples, e.g. WebCodecs
- The MIT License. Used in a number of open-source tools developed in W3C.
- The 3-Clause BSD License. Used in Web Platform Tests and the WebGPU Conformance Test Suite for instance.

The list of features in itself could come with another license too. For instance, the actual browser-specs data is released under the terms of the CC0 license, same as browser-compat-data. Perhaps something worth doing here as well?

Side note: reports that the CG could potentially publish would be published with different licenses: the [W3C Community Contributor License Agreement](https://www.w3.org/community/about/process/cla/) (CLA) for drafts and the [W3C Community Final Specification Agreement (FSA) Deed](https://www.w3.org/community/about/process/fsa-deed/) for final reports. These don't apply to code though.

**Comment by foolip** [comment]
This was resolved in https://github.com/web-platform-dx/web-features/pull/294.
