### ISSUE TITLE
animation-timeline

### ISSUE THREAD

**Issue by SachaG** [web-platform-dx/web-features#2004]
### Specification

https://www.w3.org/TR/css-animations-2/#propdef-animation-timeline

### Description

The animation-timeline [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) property specifies the timeline that is used to control the progress of a CSS animation.

### Browser support

https://caniuse.com/mdn-css_properties_animation-timeline

**Comment by ddbeck** [comment]
Thanks for opening this issue. I think this is covered by https://github.com/web-platform-dx/web-features/blob/main/features/scroll-driven-animations.yml. Do we need an "also known as" in the description? Or am I confused about what this is covering?

**Comment by ddbeck** [comment]
Ah, I see now that it looks like we created a single feature, `scroll-driven-animations` that encompasses:

- https://github.com/web-platform-dx/web-features/issues/2002
- https://github.com/web-platform-dx/web-features/issues/2003
- https://github.com/web-platform-dx/web-features/issues/2004 (this issue)

Do I have that right? I don't know a lot about the feature(s), so I'm not sure if it makes sense for these properties to be understood as separate features. I'd appreciate hearing your opinion.

**Comment by SachaG** [comment]
I'm also not sure to be honest, basically I just search the page for `timeline` and couldn't fine these features.

**Comment by captainbrosset** [comment]
My preference would be to keep these together for now. Sure, they are independent properties, but they get used together by developer to achieve one thing only: animating on scroll. 

But maybe @bramus can help shed some light here. Do you think the properties mentioned above are seen as individual things by developers, or only as a group where they use everything at the same time?

**Comment by bramus** [comment]
Technically speaking, `animation-timeline` is bucketed under CSS Animations / Web Animations, as it allows you to change the timeline of an animation.

Practically speaking there are only the `DocumentTimeline` and the `ScrollTimeline`s which you can use with it, so it kinda makes sense to keep it grouped with scroll-driven animations.

In the future more types of timelines might come into existence, but today that’s not the case. All that to say that I’m with Patrick on this: keep it grouped (for now).

**Comment by ddbeck** [comment]
It sounds like the problem is that the existing feature is not searchable. I've opened https://github.com/web-platform-dx/web-features/pull/2020 to attempt to fix this (and the related issues).
