### ISSUE TITLE
Add a coverage artifact to web-features releases

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#2021]
We should have an artifact like `coverage.json` on web-features releases on GitHub that reports:

- How many BCD keys exist (in scope for web-features, i.e., not webextensions)
- How many BCD keys have been assigned to a feature

Eventually, we'll cover all of BCD and this will not be interesting, so I don't think we need to add it to the package itself.

Prompted by https://github.com/GoogleChrome/webstatus.dev/issues/793.

**Comment by ddbeck** [comment]
> But I wanted to ask if you think this will be something that will be tracked long term (as more features are added)?

I don't think so. My expectation is that we'll (hopefully soon) get to the point where every BCD feature is tagged and new BCD features get tagged at inception (we're looking at ways to assign feature IDs before the feature ships). 100% coverage ought to be the norm.

> If it is something truly temporary, we can discuss some options like manually hosting a publicly accessible JSON blob.

Honestly, I expect to reach >95% coverage in November or December (and the last fraction will likely be non-standard and deprecated features). This ought to be very short-lived. 😄

**Comment by jcscottiii** [comment]
If it's that short term, you could just tell me a number and I'll figure it out. Or put it in the release notes text to let everyone know the progress. It doesn't have to be machine readable.

**Comment by ddbeck** [comment]
Given https://github.com/GoogleChrome/webstatus.dev/issues/793 this seems to be working. I'm going to close this up. But feel free to comment if there's more to do. Cheers!

**Comment by jcscottiii** [comment]
Thanks for everything @ddbeck!
