### ISSUE TITLE
Having a term for "Baseline" (with no year)

### ISSUE THREAD

**Issue by dfabulich** [web-platform-dx/web-features#207]
In discussing "Baseline" here in this repository, it's been a challenge to talk about the difference between "Baseline" and "Baseline 2023."

For example, in #175, I argue that MDN shouldn't refer to "Baseline" without also using a year, e.g. "Baseline 2023," "Baseline 2024," etc.

I think there needs to be a term for the non-year term "Baseline," a term that applies to "Baseline" but not to "Baseline 2023," at least so we can use this term in conversation here in the repository.

Here are some ideas for terms we could use to refer to "Baseline" that definitely don't mean the current year's "Baseline 2023":
* Dynamic Baseline
* Moving Baseline
* Living Baseline
* Variable Baseline
* Fluid Baseline
* Non-year-based Baseline

(I sorted these in order of my personal favorite.)

Here are terms that I think we should not use for this purpose, because it's ambiguous whether you mean "Baseline" or the current year's "Baseline 2023"
* Just "Baseline"
* Current Baseline
* Latest Baseline
* Baseline Now
* Active Baseline
* Stable Baseline
* Today's Baseline

Here are other terms I thought of that don't sound right to me, because it makes it sound like the _features_ are not yet stable.
* Unstable Baseline
* Fluctuating Baseline

**Comment by styfle** [comment]
I we assume that Baseline is versioned, then I think "Latest Baseline" seems to be the easiest to understand without needing a glossary to lookup the definition. We already say "Latest Chrome" or "Latest Safari" to mean the most recent version so "Latest Baseline" sounds natural to me.
