### ISSUE TITLE
Blog: On browser compatibility and support baselines

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#218]
I want highlight the excellent https://molily.de/browser-compatibility-baseline/ by @molily for discussion.

The argument is that Cascade Layers is still too new to call Baseline, and can't be used without concern by web developers.

**Comment by foolip** [comment]
The discussion in https://github.com/web-platform-dx/feature-set/issues/174 and https://github.com/web-platform-dx/feature-set/issues/190 is very relevant to this.

Also cc @dfabulich.

**Comment by atopal** [comment]
Closing this as we have updated our Baseline definitions to reflect the complexity of availability. We now have Baseline widely available, and Baseline newly available to cover both ends of the spectrum, and Baseline years to provide more flexibility still.
