### ISSUE TITLE
Baseline: Define Baseline as "when all major vendors agree"

### ISSUE THREAD

**Issue by dfabulich** [web-platform-dx/web-features#225]
I had an idea that would get us closer to defining Baseline based on market share, while still allowing Baseline to have a simple definition that doesn't incorporate the complexity of measuring market share.

We could define Baseline like this: "a feature is Baseline when all four major browser vendors agree that the feature is widely deployed and safe to use without a polyfill."

As a matter of governance, there could be a quarterly/annual meeting, and browser vendors would meet at that meeting. If any vendor disagreed that a feature was widely deployed and safe to use, then the feature would not be marked Baseline at that meeting.

Any browser vendor could nominate a feature for discussion, and, as a matter of fact, it seems likely that at least one vendor would presumably suggest that a feature be considered "Baseline" when it achieves 95% coverage on caniuse/StatCounter, but we can make current data available from other data sources as well (at least RUM archive, and presumably Cloudflare Radar once they make browser version data available). The vendors would also have access to their own private telemetry for the purposes of making this decision, which they would not have to actually share.

The vendors would decide for themselves about which data sources to trust ("it's at 95% on caniuse but 93% according to RUM archive, let's give it a little more time"), and the vendors themselves could decide what market share threshold to use, perhaps based on shared developer survey data, or based on surveys they run themselves. The vendor could also consider subtle complexities ("well, it's at 95% coverage, but Browser vX had a major bug that wasn't fixed until vY, so we think it's not really safe yet; let's discuss again next quarter/year").

**Comment by tidoust** [comment]
Closing the issue as addressed: the group converged on a [baseline definition](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md) and adopted a [governance document](https://github.com/web-platform-dx/web-features/blob/main/GOVERNANCE.md). The definition, to be reviewed at least once per year, relies on a core browser set. Governance is not delegated to browser vendors (although they are welcome to the discussion).
