### ISSUE TITLE
How do we make sure our Baseline definition is tested with devs instead of endless bikeshedding?

### ISSUE THREAD

**Issue by atopal** [web-platform-dx/web-features#237]
This was one of the issues we prioritized during our workshop on Baseline on June 16.

**Comment by tidoust** [comment]
Discussed during the [27 July baseline meeting](https://docs.google.com/document/d/1ree75ImLZjf60lTZ3BhCaLHygxgywr7SBXp-q0xPs8A/edit#heading=h.e1o7ge1hf4t1)

**Comment by tidoust** [comment]
Closing the issue as addressed. The group converged on a Baseline definition end of last year, deployed on MDN and Can I Use. The group is actively collecting feedback from devs, both through report forms present in Baseline banners and discussions with libraries maintainers, and expects to refine the definition (at least once per year) based on feedback received.
