### ISSUE TITLE
Adopt a governance document

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#241]
~~Description forthcoming. Opening now a placeholder now, for a link in the WebDX meeting notes.~~

At present, the feature-set repo is controlled by the repo committers, with no delegation or formal decision-making process beyond habit and preference. We ought to adopt a governance document and process that establishes guardrails against unwanted unilateral action and lowers a ladder to contributors to take increasing ownership of the project.

In the 22 June 2023 WebDX CG general meeting, I proposed adopting a governance document based on the [mdn/browser-compat-data governance model](https://github.com/mdn/browser-compat-data/blob/main/GOVERNANCE.md). See [web-platform-dx/feature-set governance plan proposal on Google Docs](https://docs.google.com/document/d/1wwXjQMYB027ztmt4TKJgvPUGNJkPirVzHhSA7r0xT44/edit) for more information on:

- Why we should adopt something like BCD's governance doc
- What we can learn from BCD's experience
- How we can bootstrap the governance group in the short term

The [linked document](https://docs.google.com/document/d/1wwXjQMYB027ztmt4TKJgvPUGNJkPirVzHhSA7r0xT44/edit) is open to comments and suggestions, or you can comment here.

**If you'd like to nominate yourself to help edit and adopt the governance document, please mention it below.**

**Comment by ddbeck** [comment]
For the record, I'm nominating myself to the interim governance group and volunteering to shepherd the document editing process.

**Comment by atopal** [comment]
I'm also nominating myself for the interim governance group.

**Comment by dfabulich** [comment]
I'd nominate myself.

**Comment by LeoMcA** [comment]
I'm nominating myself to the interim governance group.

**Comment by ddbeck** [comment]
@dfabulich Could you email me (email in profile), from your preferred email address for this project? I have a draft governance doc to share. Thank you!

**Comment by Elchi3** [comment]
I'm nominating myself for the interim governance group.

**Comment by ddbeck** [comment]
Over the last few weeks, a draft governance document has been reviewed and edited by the interim governance group. We're now opening up this process to other members of the WebDX community. You can read, comment, or add suggestions to [the draft governance doc in Google Docs](https://docs.google.com/document/d/1TE5w47oavepsqMMEzm3sAEq2iSQQ2R1RsZQxzRbRays/edit), or you can leave a comment on this issue. Not a lot has changed from the BCD doc that this is based on, but some highlights include:

- Adding project- and organization-specific details (e.g., referencing the W3C CEPC as a code of conduct, mentioning feature descriptions and statuses, etc.).
- Putting the Baseline definition (and other feature status definitions) and changes to the statuses themselves under control of the Owners group.
- Explicitly calling for the owners to exhaust attempts to reach a consensus before forcing a vote.
- Explicitly making Peer and Owner nomination deliberations private (to avoid needlessly embarrassing nominees who can't achieve consensus or pass a vote).
- Setting a quarterly-or-better meeting cadence, for resolving outstanding questions.

All that said, I imagine that once we adopt a document, it'll be revised over time as we gain practical experience with it.

I'm looking forward to your comments here or on the doc!

**Comment by ddbeck** [comment]
This was fixed by https://github.com/web-platform-dx/web-features/pull/359. Thanks everyone!
