### ISSUE TITLE
Navigable list of all features

### ISSUE THREAD

**Issue by Sammeeey** [web-platform-dx/web-features#245]
I just found the *baseline* badge on the page of [MDN's `order` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/order) & I really like the idea (of the list and of the badges on MDN).

Would be great to have a navigable list of all the stable features somewhere (e.g. in the mdn web docs)!

From my personal point of view this would be great - especially for beginners - to know what to learn with higher priority.

**Comment by foolip** [comment]
@Shinigami92 has built such a tool in https://shinigami92.github.io/baseline-green/ with some great filtering capabilities.

**Comment by Shinigami92** [comment]
> @Shinigami92 has built such a tool in https://shinigami92.github.io/baseline-green/ with some great filtering capabilities.

Just ping me in that repo via issue when I should update the files.
They are downloaded into the repo to prevent getting rate limited by GitHub.

**Comment by atopal** [comment]
Closing this as we have even more options now: 
* [The web platform dashboard](https://webstatus.dev/)
* [The Web features explorer](https://captainbrosset.github.io/web-features-explorer/)
