### ISSUE TITLE
Report time-to-interop or time-to-Baseline

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#393]
At the [Beyond Interop session at TPAC 2023](https://www.w3.org/2023/09/13-beyond-interop-minutes.html), @dontcallmedom suggested that web-features might be used, at least in part, to track a feature's whole time-to-interoperability or time-to-Baseline. This could give feedback to working groups, so they know how long it takes for a feature to get wider support. For instance, a possible application might be to report on whether web features are taking more or less time to reach consensus then interoperability.

A fairly straightforward intermediate step might be to start calculating something like _time from first implementation to interoperability_, which would have some utility by itself.

Some questions:

- What's the starting point for a feature, pre-implementation? (e.g., first draft of a feature's spec? Some publication status?)
- Where do we get this data? (e.g., should it live here, or in webref or browser-specs?)

Right now this is somewhat speculative as there's no obvious consumer for such data (yet). I'm logging an issue for this here to get it out of my notes and to-do list.

**Comment by foolip** [comment]
I think the simplest starting point would be first shipping implementation in the core browser set. I don't think there's an earlier time which we could always determine with confidence.

**Comment by ddbeck** [comment]
Closing this as a duplicate of https://github.com/web-platform-dx/web-features/issues/714, which has more specific discussion and includes consumer input.
