### ISSUE TITLE
Validate compat_features in CI tests

### ISSUE THREAD

**Issue by tidoust** [web-platform-dx/web-features#395]
It seems relatively easy to end up with a typo in compat_features entries, as in https://github.com/web-platform-dx/web-features/pull/280#discussion_r1363429979. These entries could be checked in CI tests to make sure that they exist in the latest version of the browser-compat-data package.

(Same thing for references to Can I Use)

**Comment by ddbeck** [comment]
This was resolved by https://github.com/web-platform-dx/web-features/pull/787 and https://github.com/web-platform-dx/web-features/pull/1343.
