### ISSUE TITLE
Allow only one usage_stats link per browser

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#447]
https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/webvtt.yml links 3 Chrome use counters, which seemed like a good idea at the time.

But it's not a very good idea. This means that consumers won't know which use counter is most representative for the feature.

I'd like to fix this for WebVTT and then disallow multiple chromestatus.com links for a single feature.

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/528 is a counter example for this. That feature has two entry points, the `CompressStream` and `DecompressionStream` features. To pick one use counter, we'd need to assume which is going to have the highest usage.

**Comment by ddbeck** [comment]
I think I'd be able to have a better idea of what the usage stats field is meant to do to give an opinion on this issue.

I kinda thought the application was a cross-reference: _this_ feature is associated with _that_ usage stat (and, implicitly, it's on you to decide how to interpret that set of cross-references). But this issue implies that maybe it's something closer to _this feature's usage [in this browser] is best understood through this link_. What'd you have in mind, @foolip?

**Comment by foolip** [comment]
To keep things simple, ideally I would like this to be a single representative use counter for each feature (per browser). By representative I mean something as close to the "real" usage of the feature as possible, avoiding counting no-op uses of a feature if possible.

For APIs this usually means measuring the single entry point to the API, often a constructor or method. But some APIs have multiple entry points or are actually composed of multiple independently useful sets of APIs.

**Comment by ddbeck** [comment]
(ugh, wrote this days ago and forgot to press the green button).

So, maybe a guideline, rather than absolute restriction, is in order. Something like this?

> For each browser where stats are available, add a URL to `usage_stats` that best represents the feature's usage in the browser.
> 
> If a browser has multiple stats for a feature, then avoid comprehensiveness and use as few URLs possible. Choose stats for the most representative entry point(s) to that feature, places where web developers are likely to start exposure to a feature.
>
> For example, given many stats for grid, choose the stats for an entry point such as `display: grid`; don't include stats for every grid property and value. But for a feature like [compression streams](https://github.com/web-platform-dx/web-features/pull/528), include stats for both the `CompressStream` and `DecompressStream` interface entry points.

**Comment by foolip** [comment]
@ddbeck that sounds just about perfect!

**Comment by foolip** [comment]
Hmm, trying to apply that guideline to WebVTT, the "entry point" language might be a problem.

https://chromestatus.com/metrics/feature/timeline/popularity/409 counts whenever we construct a C++ `VTTCue` object, but that vastly overcounts how often WebVTT is actually used. The WebVTT parser, invoked for `<track src=subtitles.vtt>`, is much lower:
https://chromestatus.com/metrics/feature/timeline/popularity/2891

And WebVTT being actually rendered (by the browser) is lower still:
https://chromestatus.com/metrics/feature/timeline/popularity/410

I think we run into the problem of potential and actual usage here. All we can know here is the actual usage, which depends on users actually watching some video with subtitles. That's necessarily lower than the potential usage, which is the usage if every single user did so.

How about we add this:

> If the entry point(s) for a feature are commonly used for feature detection, fingerprinting, or otherwise are not representative of the actual use of the feature, prefer a stat measuring the user-observable effects of the feature and add a comment about the choice made.

**Comment by captainbrosset** [comment]
Not all browsers are going to have usage stats available. Not all features either. Also, not all usage stats are going to be something we can always fully trust. Finally, web-features' main goal is to catalog features and give their baseline status.

Because of all this, I don't think we should try to enforce any kind of rules about this list of links. I'm not against a guideline, and I think the one in the previous comment is probably fine, but I would also add some documentation on the repo, for consumers, that says something like "Links to usage stats are only informational, and may not always represent the true usage of a feature across all supported browsers. Use at your own risks" (or something nicer).

**Comment by foolip** [comment]
That would be fine with me, since I'm the one curating the Chrome use counters here, and I also know how I'd like to use it. (Which is simply to sort features by usage in a spreadsheet, that sort of thing.)

**Comment by ddbeck** [comment]
Yeah, that seems fine to me too. I like the idea of documenting this better for consumers and contributors. I think we can take up a general posture for URLs to say, roughly, this is a cross-reference to information that relates to this feature, not a definitive or authoritative statement about that feature.

So there are two actions here:

- Add a guideline for setting usage_stats URLs (with Philip's addendum)
- Document `usage_stats` in the package README with a description of the field (could probably stand to do that for others, but starting with one would be nice)

**Comment by atopal** [comment]
This was solved by us deciding to use web-features-ids in usage stats instead of keeping track of them in web features.
