### ISSUE TITLE
Feature Request: Human Friendly Name for Feature Definitions

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-dx/web-features#490]
Requirement(s):
1. While processing a given [feature-group-definition](https://github.com/web-platform-dx/web-features/tree/main/feature-group-definitions),
  it would be nice to have a human friendly name for the feature.

Current problem:
- Some feature files use kebab-case like `idle-detection`. And I could convert the kebab casing to title case (e.g. Idle Detection). But not all features do that.
- Some feature file names may be too vague. (e.g. grid.yml). And the desired name may not be derivable from the filename (e.g. would want to use `CSS Grid`)
- Some features have a caniuse field that uses kebab case. But not all features have that. And some may not convert correctly if applying kebab to title casing conversions. (e.g. `caniuse: css-grid` -> `Css Grid` is not desirable)

Instead of having multiple ways to derive the name, I think having a field like `full_name` would be helpful.

**Comment by ddbeck** [comment]
Yes, I very much like this idea. 

I suspect we'll want to preserve the option of more than one reader-friendly field, along the lines of:

- Short name: "Grid", "Temporal", "`<dialog>`"
- Medium name: "CSS Grid", "Temporal API", "The `<dialog>` element"
- [Long name left as an exercise to the reader]
- Short description: "Two-dimensional page layout made up of rows and columns…", "A date and time API and successor to `Date`…", "An element that embeds an image in the page…"

We won't need these all at once, but I suspect we'll eventually want them all eventually (e.g., for sending new features to caniuse, for MDN to generate links between features, etc.).

Based on @jcscottiii's suggestion here, a medium-length name has an immediate application and is the place we should start?

**Comment by foolip** [comment]
I think we should start with descriptions that disambiguate all features from each other, and would look sensible if presented as an alphabetical list of all features.

Like for identifiers, I think we should avoid prefixes and suffixes in most cases. A lot of time it would just be the identifier capitalized.

**Comment by foolip** [comment]
I'm starting with short names in https://github.com/web-platform-dx/web-features/pull/545.
