### ISSUE TITLE
Visualize BCD features that still need to be handled

### ISSUE THREAD

**Issue by tidoust** [web-platform-dx/web-features#538]
This was discussed in [last week's WebDX meeting](https://docs.google.com/document/d/1ree75ImLZjf60lTZ3BhCaLHygxgywr7SBXp-q0xPs8A/edit#heading=h.vn824ksysie).

The idea would be to create a burndown chart with the number of BCD features that still need to be addressed.

Other metrics raised during the discussion that may be worth tracking and visualizing:
- The number of new features added to BCD, since that's a growing target
- Can I Use key coverage, noting that Can I Use keys that are somewhat arbitrary may never be covered in web-features, on purpose.
- The [list of BCD entries that are going to turn "Baseline high" this year](https://docs.google.com/spreadsheets/d/1mBF49ZqtE_uZ58hR0xlb1uygqE7DOWuTHVaMLZd8auo/edit?resourcekey=0-yopuDeseph8VO-StzYjuBQ#gid=1238114670).
- Possibly the list of BCD entries that are going to turn "Baseline low" this year, but that's more guesswork.
- Some measure of the usefulness of group features created in web-features.

I also note that the ability to explore features that are not in web-features was raised in https://github.com/web-platform-dx/web-features/issues/536#issuecomment-1907286653. This could perhaps be part of this tooling/visualization as well.

**Comment by tidoust** [comment]
Another suggestion inspired from https://github.com/web-platform-dx/web-features/issues/536#issuecomment-1907286653 would be to create another burndown chart with the list and number of features already in web-features that don't yet have a `status.baseline` field.

**Comment by ddbeck** [comment]
Between https://github.com/web-platform-dx/web-features/issues/666 and https://github.com/web-platform-dx/web-features/issues/788, I think this complete.

François's suggestion to report how many features lack a status is no longer necessary, since all features require a status since https://github.com/web-platform-dx/web-features/pull/899.
