### ISSUE TITLE
Guideline for naming "basic" features

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#653]
We so far have two features with "basic" in their description, name "Basic JavaScript arrays" and "Basic typed arrays".

These features mean roughly "the earliest iteration of this API, only the bits that were cross-browser from the beginning".

caniuse.com has 4 such entries which can be found at https://caniuse.com/?search=basic.

I propose that we follow the style of caniuse.com and use "(basic support)" as suffix for the _name_ of such features.

cc @Elchi3

**Comment by foolip** [comment]
@Fyrd do you have preferences for how we name features like this? Would "initial support" capture how you've been using "basic" in caniuse.com?

Also cc @ddbeck

**Comment by Elchi3** [comment]
+ 1 to "Initial JavaScript arrays", "Initial typed arrays".

**Comment by foolip** [comment]
Alright, so weighing together the excitement on various points, I think we should put (initial support) as suffix on the short name. I've sent https://github.com/web-platform-dx/web-features/pull/673 to show what that would look like.

**Comment by foolip** [comment]
Closing as merging https://github.com/web-platform-dx/web-features/pull/699 didn't auto-close this. Perhaps it's the commit message that does the trick, not sure.
