### ISSUE TITLE
Shorten descriptions back to 280?

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#705]
In https://github.com/web-platform-dx/web-features/pull/704 I increased the max description length to 300, since I couldn't quickly find a way to reduce the length of the Oklab description to below 293 characters.

Should we go back to 280, or just live with 300?

**Comment by atopal** [comment]
I guess we're still finding out what a reasonable length is and looks like it's at least 293 characters, so I would go with 300 for roundness, and come back to it if we ever find we need more than that.

**Comment by foolip** [comment]
Sure, let's live with it. I just don't want to bump it every time we accidentally break the build with a long description :) When current PRs (which have already passed CI) are out of the queue that should not be a problem.
