### ISSUE TITLE
Release the schema files in the the GitHub Release

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-dx/web-features#715]
Building on https://github.com/web-platform-dx/web-features/issues/714

It would be nice to include the schema files in the GitHub Release so that I know the format of the data.json I am about to parse.

I wouldn't consider this a high priority unless there are breaking changes to the schema.

**Comment by foolip** [comment]
@jcscottiii do you use the two JSON schema files directly, or do you need a single JSON schema file that you can validate the whole `data.json` with?

**Comment by foolip** [comment]
@jcscottiii can you share the quicktype invocation that would get us a single JSON schema file? If that just works, we can publish that and save you some trouble.

**Comment by ddbeck** [comment]
We now publish the JSON Schema files alongside the data, both in the npm package and GitHub releases as artifacts, starting with [v1.0.0](https://github.com/web-platform-dx/web-features/releases/tag/v1.0.0). Let me know if you need anything else here. Cheers!
