### ISSUE TITLE
Policy around specification links, working draft vs published version

### ISSUE THREAD

**Issue by romainmenke** [web-platform-dx/web-features#724]
https://github.com/web-platform-dx/web-features/blob/e8e4af316b6f4f25a1e33012381b7564b8d3efa1/feature-group-definitions/lab.yml#L3C15-L3C31

The relevant sections for `lab` are all present and up to date in the published version : https://www.w3.org/TR/css-color-4/

So I think that maybe this was just an oversight?

-----

Should there be a policy and maybe even tooling around such specification links.
Ideally all features link to published versions and never to working drafts.
But in practice a feature can be described only in a draft while also having been implemented by all vendors.

Maybe draft spec links need an associated date in the web features data?
Then it is relatively easy to compare that date with the last publish date and assert if the links should be updated.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-dx/web-features/pull/725 to document what the current code does. It is different from BCD which does allow a larger variety of URLs:

https://github.com/mdn/browser-compat-data/blob/fd1cb702c59712fc3ef2056ed3a846292e3ae8c3/test/linter/test-spec-urls.ts#L41-L53

On what the policy should be, I think we should prefer nightly URLs for a few reasons:

- It's what's almost always done in BCD and thus what's shown on MDN ([example](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab#specifications))
- It's what we do in WPT ([example](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/META.yml))
- Implementers should basically never look at snapshots and always at the latest version of the spec.

If there's a consumer use case I think we could arrange to also put the latest snapshot of the spec in a new field clearly marked as such.

**Comment by romainmenke** [comment]
Makes sense, thank you!

> If there's a consumer use case I think we could arrange to also put the latest snapshot of the spec in a new field clearly marked as such.

I do not think there is such use case, or at least, can't think of any :)
