### ISSUE TITLE
`css.types.length-percentage.ic` doesn't exist

### ISSUE THREAD

**Issue by romainmenke** [web-platform-dx/web-features#730]
https://github.com/web-platform-dx/web-features/blob/971fee52bddbf710e0f8def3eaf7b618c1f664fe/feature-group-definitions/ic.yml#L6C5-L6C35

see : https://github.com/mdn/browser-compat-data/blob/main/css/types/length-percentage.json

**Comment by foolip** [comment]
Oops, I guess BCD changed. Fixed in https://github.com/mdn/browser-compat-data/pull/22697 + https://github.com/web-platform-dx/web-features/pull/731. Thanks for reporting!
