### ISSUE TITLE
Publish descriptions

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#736]
In review we have started adding descriptions to new features as a matter of course. Let's add the missing ones and then add this to the schema and published data.

**Comment by captainbrosset** [comment]
Taking a crack at this now. Not sure how far I will get, but I'll start.

**Comment by atopal** [comment]
The guidelines for descriptions were discussed here https://github.com/web-platform-dx/web-features/issues/532#issuecomment-1986089385

**Comment by ddbeck** [comment]
Description guidelines came up in the WebDX call today. I opened https://github.com/web-platform-dx/web-features/pull/789 to capture as much as I could of the description reviews/edits so far.
