### ISSUE TITLE
Turn on branch protection rules

### ISSUE THREAD

**Issue by ddbeck** [web-platform-dx/web-features#768]
We should turn on branch protection rules, requiring an approving review and tests to pass before merging to `main`.

This is probably a good idea in general, but but it would also be nice to set a PR to [automatically merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) from time to time. A PR like https://github.com/web-platform-dx/web-features/pull/761 is probably a good example: as soon as the tests can pass, it ought to merge.

**Comment by foolip** [comment]
I agree 👍

**Comment by ddbeck** [comment]
OK, on `main` I've turned on the following:

- No deleting the branch (duh)
- Require a pull request with one or more write-access approvers before merging
- The `build` and `test` GitHub Actions must pass before merging (i.e., you can't push directly to `main` without with the checks passing on the commit—that is, the commits must be on another branch first)

I think that's the minimal set we need. If this stops anyone from doing something normal, let me know—the settings allow various exemptions and adjustments. 

And if there aren't any problems in the next couple days, feel free to close this.
