### ISSUE TITLE
Publish compute-baseline to npm

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#818]
In order for @LeoMcA to use this on MDN, we need to publish it.

@ddbeck is it just a question of running `npm publish`?

**Comment by ddbeck** [comment]
@foolip I think there's a few little things to do first:

- [ ] Remove `"private": true` from [`package.json`](https://github.com/ddbeck/web-features/blob/1a09c0f0472fb078aabd63eb3fcdb68baa762b41/packages/compute-baseline/package.json#L2)
- [ ] Copy over `LICENSE.txt` at publishing time (kinda like [we do in `build.ts`](https://github.com/ddbeck/web-features/blob/1a09c0f0472fb078aabd63eb3fcdb68baa762b41/scripts/build.ts#L11-L23))
- [ ] Add a (bare-bones) `README.md` to `/packages/compute-baseline`

**Comment by captainbrosset** [comment]
@ddbeck seems like most of the work is done and all is left is making the package public and publishing it. I could make use if it was published.

**Comment by ddbeck** [comment]
@captainbrosset Yes, I'm working on this. See https://github.com/web-platform-dx/web-features/pull/961.

**Comment by ddbeck** [comment]
And we're live: https://www.npmjs.com/package/compute-baseline/v/0.1.0-dev-20240425134050-57ad8a7
