### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#938]
Let's automate releases more, so that we can quickly release and publish both a GitHub release with `data.json` and the npm package.

- [x] Automate publishing to NPM when a tag is pushed (https://github.com/web-platform-dx/web-features/pull/1479)
- [ ] Set up something like https://github.com/googleapis/release-please to prepare releases in a pull request. Or something that maintains a draft GitHub release.

**Comment by foolip** [comment]
@jcscottiii suggested that we can copy from https://github.com/mdn/browser-compat-data/blob/main/.github/workflows/release.yml

There are also some goodies in https://github.com/w3c/webref/blob/main/.github/workflows/release-package.yml to take inspiration from.

**Comment by ddbeck** [comment]
https://github.com/web-platform-dx/web-features/issues/11#issuecomment-1415954119 outlined some work done or planned for automating releases as well.

**Comment by foolip** [comment]
@ddbeck and I have discussed this a few times, and concluded it makes sense to work backwards, first automating the publishing to NPM, then the creation of tags and GitHub releases. I'll update the description with a list of checkboxes.

**Comment by foolip** [comment]
These are the steps I take to make a release manually now:

- Send a PR to update packages/web-features/package.json and ackages/web-features/package-lock.json (I edit the first and then run `npm i` to update the second.)
- Wait for that PR to be approved
- Merge the PR and immediately go to https://github.com/web-platform-dx/web-features/releases/new
- Fill in the tag name vX.Y.Z manually as both the tag and release title
- Click "Generate release notes"
- Search for "<" and make sure all element names are quoted with backquotes
- Locally, update main and run `npm run build` and `npm run build:extended`
- Upload data.json, data.extended.json and data.schema.json as release artifacts
- Publish GitHub release

The last step creates the Git tag. So far I have been running `npm publish` manually but that should now get done automatically.

I also take make sure I don't have a stale checkout or anything built from a previous state of the repo when I publish. Sometimes by running `git clean -fdx` before I start, and sometimes by just running `npm ci` in the root and inside packages/web-features.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-dx/web-features/pull/1559 and https://github.com/web-platform-dx/web-features/pull/1560, and believe that with those two landed, releases are automated enough to not be a blocker for https://github.com/web-platform-dx/web-features/issues/1240.
